CREATE DATABASE Test1
GO

USE Test1
GO

CREATE TABLE Users (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(50) NOT NULL CHECK (username NOT LIKE '%[^a-zA-Z0-9]%')
);

CREATE TABLE Posts (
    id INT IDENTITY(1,1) PRIMARY KEY,
    title NVARCHAR(255) NOT NULL,
    content NVARCHAR(MAX) NOT NULL,
    author INT NOT NULL,
    created_timestamp DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (author) REFERENCES Users(id)
);